language: java
jdk:
  - openjdk8

before_script: chmod +x ./gradlew

git:
  depth: 1

script: echo "Initializing tests ..."

jobs:
  include:
    - stage: Full run
      install: skip
      script: ./gradlew clean compileJava compileTestJava test jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)